sudo: false
dist: trusty
language: gcc
compiler:
- gcc
addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - zip
script:
- mkdir out zip
- x86_64-w64-mingw32-gcc main.c -o out/_Launcher.exe
- find  ./res/* -maxdepth 1 -type d -printf '%f\n' > resl.txt
- xargs -a resl.txt -I{} x86_64-w64-mingw32-windres res/{}/res.rc -o res/{}.o
- xargs -a resl.txt -I{} x86_64-w64-mingw32-gcc main.c res/{}.o -o zip/{}.exe
- cd zip
- zip ../out/icons.zip *
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: LErGUUK/E5nRqR+n2AggRR9dU2+DD7KGSZf5kHeNJkmhr/WTPt2LU1LbCNSpd7uzKgOrx24ZkmOiWLzgY5LS8j3BN7W9Nm8Yh6U+wRwuHm86FxkJF0tutL4OEhnME+T5BbGde47q7F23JHwvR033EDP4CUOXIHBdCu+UYHbfQl7yZUUdUKAVYcMZVcVvFV2EgPAZUlUBWQXB8MGtN5dOHKPSqJOyHT6lM9lDAuYfrP9jrxd/93eQIFR12tyRYW360oSjXKJLSdTUdwquQYu/oxFjJWr17T+1CK3KFxhkOxA+ecUEQU7GmUolFuftMp5rxul8ehYNwI8TBE8SJ7WoMWJeLXO8lCLnou5AYkQDgah8C5ubYzM9zt7b2xKUmTva5Tb8nFq24lu2ftlc5JyLccpvabWG/hjugeoohcpngxXhVB3JsNqqrtkc2qdOPCczAETiis7XVQ8DDLehuiFlSrYOtXAkTZxzyX5WgmJakUgxHFr31v+sljlg/RICo60wDdf50sCxfjVaXtiu4bTQQMlVDctyUanjPpFNFoHBfwd7PHBxr9X+996yILVthLLIKc39WPmvkVU+ctQxfjFWEZARnpTxO9JPTTe/9jhpkQxvvlQkY5HuauKo8/OMJ2uZ8GTusvus8SmDQglJxuNMT7hIwrbybcS4E7aIUNJpo5Q=
  file_glob: true
  file: 'out/*.{exe,zip}'
  on:
    repo: yuk7/WSL-DistroLauncher
    tags: true
    all_branches: true
  skip_cleanup: true
